constellation_orderboard/urls.py
from django.conf.urls import url

from . import views

app_name = 'constellation_orderboard'
urlpatterns = [
# =============================================================================
# View Routes
# =============================================================================

    url(r'^view/list$', views.view_list,
        name="view_list"),
    url(r'^view/board/(?P<board_id>\d+)$', views.view_board,
        name="view_board"),
    url(r'^view/board/(?P<board_id>\d+)/archive$', views.view_board_archive,
        name="view_board_archive"),

# =============================================================================
# Management Routes
# =============================================================================

    url(r'^manage/boards$', views.manage_boards,
        name="manage_boards"),
    url(r'^manage/board/(?P<board_id>\d+)/edit$', views.manage_board_edit,
        name="manage_board_edit"),
    url(r'^manage/stages$', views.manage_stages,
        name="manage_stages"),

# =============================================================================
# API Routes for the v1 API
# =============================================================================

    # The API routes are divided into functional groups based on what
    # they control.  In general each group will contain the standard
    # CRUD calls, but may also contain additional calls for specific
    # objects.

# -----------------------------------------------------------------------------
# API Routes related to Board Operations
# -----------------------------------------------------------------------------

    url(r'^api/v1/board/list$',
        views.api_v1_board_list,
        name="api_v1_board_list"),

    url(r'^api/v1/board/create$',
        views.api_v1_board_create,
        name="api_v1_board_create"),

    url(r'^api/v1/board/(?P<board_id>\d+)/update$',
        views.api_v1_board_update,
        name="api_v1_board_update"),

    url(r'^api/v1/board/(?P<board_id>\d+)/archive$',
        views.api_v1_board_archive,
        name="api_v1_board_archive"),

    url(r'^api/v1/board/(?P<board_id>\d+)/unarchive$',
        views.api_v1_board_unarchive,
        name="api_v1_board_unarchive"),

    url(r'^api/v1/board/(?P<board_id>\d+)/active-cards$',
        views.api_v1_board_active_cards,
        name="api_v1_board_active_cards"),

    url(r'^api/v1/board/(?P<board_id>\d+)/archived-cards$',
        views.api_v1_board_archived_cards,
        name="api_v1_board_archived_cards"),

    url(r'^api/v1/board/(?P<board_id>\d+)/info$',
        views.api_v1_board_info,
        name="api_v1_board_info"),

# -----------------------------------------------------------------------------
# API Routes related to Card Operations
# -----------------------------------------------------------------------------

    url(r'^api/v1/card/create-on/(?P<board_id>\d+)$',
        views.api_v1_card_create,
        name="api_v1_card_create"),

    url(r'^api/v1/card/(?P<board_id>\d+)-(?P<card_id>\d+)/edit$',
        views.api_v1_card_edit,
        name="api_v1_card_edit"),

    url(r'^api/v1/card/(?P<board_id>\d+)-(?P<card_id>\d+)/archive$',
        views.api_v1_card_archive,
        name="api_v1_card_archive"),

    url(r'^api/v1/card/(?P<board_id>\d+)-(?P<card_id>\d+)/unarchive$',
        views.api_v1_card_unarchive,
        name="api_v1_card_unarchive"),

    url(r'^api/v1/card/(?P<board_id>\d+)-(?P<card_id>\d+)/move-right$',
        views.api_v1_card_move_right,
        name="api_v1_card_move_right"),

    url(r'^api/v1/card/(?P<board_id>\d+)-(?P<card_id>\d+)/move-left$',
        views.api_v1_card_move_left,
        name="api_v1_card_move_left"),

# -----------------------------------------------------------------------------
# API Routes related to Stage Operations
# -----------------------------------------------------------------------------

    url(r'^api/v1/stage/list$', views.api_v1_stage_list,
        name="api_v1_stage_list"),
    url(r'^api/v1/stage/create$', views.api_v1_stage_create,
        name="api_v1_stage_create"),
    url(r'^api/v1/stage/([\d]*)/archive$', views.api_v1_stage_archive,
        name="api_v1_stage_archive"),
    url(r'^api/v1/stage/([\d]*)/unarchive$', views.api_v1_stage_unarchive,
        name="api_v1_stage_unarchive"),
    url(r'^api/v1/stage/([\d]*)/move-left$', views.api_v1_stage_move_left,
        name="api_v1_stage_move_left"),
    url(r'^api/v1/stage/([\d]*)/move-right$', views.api_v1_stage_move_right,
        name="api_v1_stage_move_right"),

# -----------------------------------------------------------------------------
# Dashboard routes
# -----------------------------------------------------------------------------

    url(r'^view/dashboard$', views.view_dashboard,
        name="view_dashboard"),

]

constellation_orderboard/templates/constellation_orderboard/board.html
{% extends "constellation_base/base.html" %}

{% block title %}{{ template_settings.organization }} -- Orderboard{% endblock %}
{% block heading %}Orderboard{% endblock %}

{% block head %}
{{ block.super }}
{% load static %}
<link rel="stylesheet" href="{% static 'constellation_orderboard/css/orderboard.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dialog-polyfill/0.4.4/dialog-polyfill.min.css" />
{% endblock %}

{% block js %}
<div id="message-toast" class="mdl-js-snackbar mdl-snackbar">
    <div class="mdl-snackbar__text"></div>
    <button class="mdl-snackbar__action" type="button"></button>
</div>
<dialog id="newItem" class="mdl-dialog">
    <h4 class="mdl-dialog__title">New Item</h4>
    <div class="mdl-dialog__content mdl-grid">
        <form method="post" action="{% url 'constellation_orderboard:api_v1_card_create' id %}" id="newItemForm" class="mdl-grid">
            {% csrf_token %}
            {{ form.stage.as_hidden }}
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell--12-col mdl-cell--bottom">
                {{ form.name }}
                <label class="mdl-textfield__label" for="{{ form.name.id_for_label }}">Name</label>
            </div>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell--12-col mdl-cell--3-col-tablet mdl-cell--bottom">
                {{ form.quantity }}
                <label class="mdl-textfield__label" for="{{ form.quantity.id_for_label }}">Quantity</label>
            </div>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell--12-col mdl-cell--5-col-tablet mdl-cell--bottom">
                {{ form.units }}
                <label class="mdl-textfield__label" for="{{ form.units.id_for_label }}">Units</label>
            </div>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label" style="width:100%">
                {{ form.notes }}
                <label class="mdl-textfield__label" for="{{ form.notes.id_for_label }}">Description</label>
            </div>
            <div class="mdl-dialog__actions">
                <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">
                    Submit Item <i class="material-icons right">done</i>
                </button>
            </div>
        </form>
    </div>
</dialog>
<dialog id="editItem" class="mdl-dialog">
    <h4 class="mdl-dialog__title">Edit Item</h4>
    <div class="mdl-dialog__content mdl-grid">
        <form method="post" action="{% url 'constellation_orderboard:api_v1_card_edit' id 0 %}" id="editItemForm" class="mdl-grid" name="0">
            {% csrf_token %}
            {{ editForm.stage.as_hidden }}
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell--12-col mdl-cell--bottom">
                {{ editForm.name }}
                <label class="mdl-textfield__label" for="{{ editForm.name.id_for_label }}">Name</label>
            </div>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell--12-col mdl-cell--3-col-tablet mdl-cell--bottom">
                {{ editForm.quantity }}
                <label class="mdl-textfield__label" for="{{ editForm.quantity.id_for_label }}">Quantity</label>
            </div>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell--12-col mdl-cell--5-col-tablet mdl-cell--bottom">
                {{ editForm.units }}
                <label class="mdl-textfield__label" for="{{ editForm.units.id_for_label }}">Units</label>
            </div>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label" style="width:100%">
                {{ editForm.notes }}
                <label class="mdl-textfield__label" for="{{ editForm.notes.id_for_label }}">Description</label>
            </div>
            <div class="mdl-dialog__actions">
                <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">
                    Submit Item <i class="material-icons right">done</i>
                </button>
            </div>
        </form>
    </div>
</dialog>
{{ block.super }}
{% load static %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/dialog-polyfill/0.4.4/dialog-polyfill.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.5/handlebars.min.js"></script>
<script>
    var board_id = "{{ id }}"
    var url_api_v1_stage_list = "{% url 'constellation_orderboard:api_v1_stage_list' %}";
    var url_api_v1_board_active_cards = "{% url 'constellation_orderboard:api_v1_board_active_cards' id %}";
    var url_api_v1_card_move_left = "{% url 'constellation_orderboard:api_v1_card_move_left' id 0 %}";
    var url_api_v1_card_move_right = "{% url 'constellation_orderboard:api_v1_card_move_right' id 0 %}";
    var url_api_v1_card_archive = "{% url 'constellation_orderboard:api_v1_card_archive' id 0 %}";
    var url_api_v1_card_edit = "{% url 'constellation_orderboard:api_v1_card_edit' id 0 %}";
    var stage_form_id="{{ form.stage.id_for_label }}";
    var edit_board_id="{{ editForm.board.id_for_label }}";
    var edit_name_id="{{ editForm.name.id_for_label }}";
    var edit_quantity_id="{{ editForm.quantity.id_for_label }}";
    var edit_units_id="{{ editForm.units.id_for_label }}";
    var edit_notes_id="{{ editForm.notes.id_for_label }}";
</script>

<script src="{% static 'constellation_orderboard/js/orderboard.js' %}"></script>
{% endblock %}

{% block content %}
{% load guardian_tags %}
{% get_obj_perms request.user for board as "board_perms" %}
{% verbatim %}
<div class="mdl-grid board" id="board" style="width:100%">
    <div class="waiting-spinner mdl-spinner mdl-js-spinner is-active"></div>
    <script id="handlebars-board" type="text/x-handlebars-template">
    {{#each stages}}
        <div class="mdl-cell mdl-cell--12-col mdl-cell--{{../mdl_width}}-col-desktop stage" id="stage_{{name}}">
        <hr class="mdl-cell--hide-desktop">
        <h3 class="stage-name">{{name}}</h3>
        {{#each cards}}
            <div id="card_{{id}}" class="inventory-item mdl-card mdl-shadow--2dp mdl-color--accent mdl-color-text--white">
                <div class="card_name mdl-card__title mdl-color-text--white">
                    <span>{{name}}</span>&nbsp;<span id="card_{{id}}_quantity">({{quantity}}{{# if units }} {{units}}{{/if}})</span>
                </div>
                <div class="mdl-card__supporting-text mdl-color-text--white">
                    <div id="card_{{id}}_notes" class="card_notes">{{notes}}</div>
{% endverbatim %}
{% if "action_move_cards" in board_perms %}
{% verbatim %}
                    <button onclick="moveItem({{id}}, 'left')" id="card_{{id}}_left_button" class="card_button card_left_button mdl-cell--hide-tablet mdl-cell--hide-phone">
                        <i class="material-icons">chevron_left</i>
                    </button>
                    <button onclick="moveItem({{id}}, 'left')" id="card_{{id}}_up_button" class="card_button card_up_button mdl-cell--hide-desktop">
                        <i class="material-icons">keyboard_arrow_up</i>
                    </button>
                    <button onclick="moveItem({{id}}, 'right')" id="card_{{id}}_right_button" class="card_right_button card_button mdl-cell--hide-tablet mdl-cell--hide-phone">
                        <i class="material-icons">chevron_right</i>
                    </button>
                    <button onclick="moveItem({{id}}, 'right')" id="card_{{id}}_down_button" class="card_button card_down_button mdl-cell--hide-desktop">
                        <i class="material-icons">keyboard_arrow_down</i>
                    </button>
{% endverbatim %}
{% endif %}
{% verbatim %}
                    <div class="card_extra_buttons">
                      <div class="card_extra_buttons_inner">
{% endverbatim %}
{% if "action_add_cards" in board_perms %}
{% verbatim %}
                        <span onclick="editItem({{id}})" id="card_{{id}}_edit_button" class="card_button card_edit_button">
                          <i class="material-icons">mode_edit</i>
                        </span>
{% endverbatim %}
{% endif %}
{% if "action_archive_cards" in board_perms %}
{% verbatim %}
                        <span onclick="deleteItem({{id}})" id="card_{{id}}_close_button" class="card_button card_close_button">
                          <i class="material-icons">close</i>
                        </span>
{% endverbatim %}
{% endif %}
{% verbatim %}
                      </div>
                    </div>
                    <div id="card_{{id}}_progress" class="progress"> <div class="mdl-progress mdl-js-progress mdl-progress__indeterminate"></div></div>
                </div>
            </div>
        {{/each}}
    </div>
    {{/each}}
    <div id="clear" style="clear:both;"></div>
    </script>
</div>
<br/>
<div class="divider"></div>
{% endverbatim %}
<div class="fixed-action-btn">
  {% if "action_manage_board" in board_perms %}
  <a href="{% url 'constellation_orderboard:manage_board_edit' id %}" class="fab">
    <button id="archive" class="mdl-button mdl-js-button mdl-button--fab mdl-button--accent">
      <i class="material-icons">settings</i>
    </button>
  </a>
  {% endif %}

  {% if "action_archive_cards" in board_perms %}
  <a href="{% url 'constellation_orderboard:view_board_archive' id %}" class="fab">
    <button id="archive" class="mdl-button mdl-js-button mdl-button--fab mdl-button--accent">
      <i class="material-icons">archive</i>
    </button>
  </a>
  {% endif %}

  {% if "action_add_cards" in board_perms %}
  <button id="showNewItem" class="mdl-button mdl-js-button mdl-button--fab mdl-button--colored">
    <i class="material-icons">add</i>
  </button>
  {% endif %}
</div>

<br/>
{% endblock %}

constellation_orderboard/templates/constellation_orderboard/dashboard.html
<div class="mdl-card__title">
    <h2 class="mdl-card__title-text">Orderboard</h2>
</div>
<div class="mdl-card__supporting-text">
    <ul class="mdl-list">
        <li class="mdl-list__item">
            <span class="mdl-list__item-primary-content">
                <i class="material-icons mdl-list__item-icon">pageview</i>
                <a href="{% url 'constellation_orderboard:view_list' %}">View Boards List</a>
            </span>
        </li>
        {% if perms.constellation_orderboard.create_board %}
        <li class="mdl-list__item">
            <span class="mdl-list__item-primary-content">
                <i class="material-icons mdl-list__item-icon">settings</i>
                <a href="{% url 'constellation_orderboard:manage_boards' %}">Manage Boards</a>
            </span>
        </li>
        {% endif %}
        {% if perms.constellation_orderboard.modify_stages %}
        <li class="mdl-list__item">
            <span class="mdl-list__item-primary-content">
                <i class="material-icons mdl-list__item-icon">settings</i>
                <a href="{% url 'constellation_orderboard:manage_stages' %}">Manage Stages</a>
            </span>
        </li>
        {% endif %}
    </ul>
</div>

constellation_orderboard/templates/constellation_orderboard/manage-boards.html
{% extends "constellation_base/base.html" %}

{% block title %}Orderboard | Manage Boards{% endblock %}
{% block heading %}Orderboard | Manage Boards{% endblock %}

{% block head %}
{{ block.super }}
{% load static %}
<link rel="stylesheet" href="{% static 'constellation_orderboard/css/orderboard.css' %}">
{% endblock %}

{% block js %}
<div id="message-toast" class="mdl-js-snackbar mdl-snackbar">
   <div class="mdl-snackbar__text"></div>
   <button class="mdl-snackbar__action" type="button"></button>
</div>
{{ block.super }}
{% load static %}
<script src="{% static 'constellation_orderboard/js/manage-boards.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.5/handlebars.min.js"></script>
<script>
    var url_api_v1_board_list = "{% url 'constellation_orderboard:api_v1_board_list' %}"
    var url_api_v1_board_unarchive = "{% url 'constellation_orderboard:api_v1_board_unarchive' 0 %}"
    var url_api_v1_board_archive = "{% url 'constellation_orderboard:api_v1_board_archive' 0 %}"
    var url_board_edit = "{% url 'constellation_orderboard:manage_board_edit' 0 %}"
    var url_view_board = "{% url 'constellation_orderboard:view_board' 0 %}"
</script>
{% endblock %}

{% block content %}
<div id="boardsCard" class="mdl-card mdl-cell--8-col mdl-cell--2-offset-desktop mdl-shadow--2dp mdl-grid">
    {% verbatim %}
    <script id="handlebars-board" type="text/x-handlebars-template">
        <div class="mdl-card__title">
            <h2 class="mdl-card__title-text">Boards</h2>
        </div>
        <div class="mdl-card__supporting-text">
            <div class="mdl-list">
            {{#if active_boards}}
            {{#each active_boards}}
                <div class="mdl-list__item">
                    <span class="mdl-list__item-primary-content">
                        <a href="{{url}}">{{name}}</a>
                    </span>
                    <span class="mdl-list__item-secondary-content">
                        <span class="mdl-list__item-secondary-action">
                          <a href="#" onclick="archiveBoard({{id}})"><i class="material-icons">close</i></a>
                          <a href="#" onclick="editBoard({{id}})"><i class="material-icons">edit</i></a>
                        </span>
                    </span>
                </div>
            {{/each}}
            {{else}}
                No active boards yet -- add one below!
            {{/if}}
            </div>
            <hr/>
            <h5>Inactive Boards</h5>
            <ul>
            {{#each inactive_boards}}
                <div class="mdl-list__item">
                    <span class="mdl-list__item-primary-content">
                        <span><a href="{{url}}">{{name}}</span>
                    </span>
                    <span class="mdl-list__item-secondary-content">
                        <span class="mdl-list__item-secondary-action">
                            <a href="#" onclick="unarchiveBoard({{id}})"><i class="material-icons">check_circle</i></a>
                        </span>
                    </span>
                </div>
            {{/each}}
            </ul>
        </div>
    </script>
    {% endverbatim %}
</div>
<div id="formCard" class="form-card mdl-card mdl-cell--8-col mdl-cell--2-offset-desktop mdl-shadow--2dp mdl-grid">
   <div class="mdl-card__title">
      <h2 class="mdl-card__title-text">New Board</h2>
   </div>
   <div class="mdl-card__supporting-text">
      <form method="post" action="{% url 'constellation_orderboard:api_v1_board_create' %}" id="newBoardForm" class="mdl-cell--12-col">
         {% csrf_token %}
         {{ form.active.as_hidden }}
         <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell--12-col mdl-cell--bottom">
            {{ form.name }}
            <label class="mdl-textfield__label" for="{{ form.name.id_for_label }}">Name</label>
         </div>
         <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell--12-col mdl-cell--bottom">
            {{ form.desc }}
            <label class="mdl-textfield__label" for="{{ form.desc.id_for_label }}">Description</label>
         </div>
         <ul class="demo-list-control mdl-list">
            <li class="mdl-list__item">
               <span id="group-header" class="mdl-cell--4-col">Group</span>
               <span class="mdl-cell--12-col permissions-header">
                  <i id="perm-none" class="material-icons perm-icon">not_interested</i>
                  <div class="mdl-tooltip" for="perm-none">No Permissions</div>
                  <i id="perm-view" class="material-icons perm-icon">visibility</i>
                  <div class="mdl-tooltip" for="perm-view">View Board</div>
                  <i id="perm-add" class="material-icons perm-icon">add_box</i>
                  <div class="mdl-tooltip" for="perm-add">Add Cards</div>
                  <i id="perm-move" class="material-icons perm-icon">swap_horiz</i>
                  <div class="mdl-tooltip" for="perm-move">Move Cards</div>
                  <i id="perm-archive" class="material-icons perm-icon">archive</i>
                  <div class="mdl-tooltip" for="perm-archive">Archive Cards</div>
                  <i id="perm-manage" class="material-icons perm-icon">settings</i>
                  <div class="mdl-tooltip" for="perm-manage">Manage Cards</div>
               </span>
               {% for group in groups %}
               <li class="mdl-list__item">
                  <span id="group-{{ group.1 }}" class="mdl-cell--4-col">{{ group.0 }}</span>
                  <span class="mdl-cell--12-col">
                     <input id="slider-{{ group.1 }}" name="group-{{ group.1 }}" class="mdl-slider mdl-js-slider group-permission" type="range" min="1" max="6" steps="1" value="1">
                  </span>
               </li>
               {% endfor %}
            </ul>
            <div class="mdl-card__actions">
               <div class="mdl-layout-spacer"></div>
               <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--primary">
                  Create Board <i class="material-icons right">done</i>
               </button>
            </div>
         </form>
      </div>
   </div>
   {% endblock %}

constellation_orderboard/templates/constellation_orderboard/manage-stages.html
{% extends "constellation_base/base.html" %}

{% block title %}Orderboard | Manage Stages{% endblock %}
{% block heading %}Orderboard | Manage Stages{% endblock %}

{% block head %}
{{ block.super }}
{% load static %}
<link rel="stylesheet" href="{% static 'constellation_orderboard/css/orderboard.css' %}">
{% endblock %}

{% block js %}
<div id="message-toast" class="mdl-js-snackbar mdl-snackbar">
  <div class="mdl-snackbar__text"></div>
  <button class="mdl-snackbar__action" type="button"></button>
</div>
{{ block.super }}
{% load static %}
<script src="{% static 'constellation_orderboard/js/manage-stages.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.5/handlebars.min.js"></script>
<script>
    var url_api_v1_stage_list = "{% url 'constellation_orderboard:api_v1_stage_list' %}";
    var url_api_v1_stage_create = "{% url 'constellation_orderboard:api_v1_stage_list' %}";
    var url_api_v1_stage_archive = "{% url 'constellation_orderboard:api_v1_stage_archive' 0 %}";
    var url_api_v1_stage_unarchive = "{% url 'constellation_orderboard:api_v1_stage_unarchive' 0 %}";
    var url_api_v1_stage_move_left = "{% url 'constellation_orderboard:api_v1_stage_move_left' 0 %}";
    var url_api_v1_stage_move_right = "{% url 'constellation_orderboard:api_v1_stage_move_right' 0 %}";
</script>
{% endblock %}

{% block content %}
<div id="stagesCard" class="mdl-card mdl-cell--8-col mdl-cell--2-offset-desktop mdl-shadow--2dp mdl-grid">
    {% verbatim %}
    <script id="handlebars-stages" type="text/x-handlebars-template">
        <div class="mdl-card__title">
            <h2 class="mdl-card__title-text">Stages</h2>
        </div>
        <div class="mdl-card__supporting-text">
            {{#if stages}}
            <div class="mdl-list">
                {{#each stages}}
                <div class="mdl-list__item stage-archived--{{archived}}">
                    <span class="mdl-list__item-primary-content">
                    <span>{{name}}</span>
                    </span>
                    <span class="mdl-list__item-secondary-content">
                        <span class="mdl-list__item-secondary-action">
                            <a href="#" onclick="bubbleUp({{id}})"><i class="material-icons bubble_up">keyboard_arrow_up</i></a>
                            <a href="#" onclick="bubbleDown({{id}})"><i class="material-icons bubble_down">keyboard_arrow_down</i></a>
                            <a href="#" onclick="archiveStage({{id}})" class="archive-stage"><i class="material-icons">close</i></a>
                            <a href="#" onclick="unarchiveStage({{id}})" class="unarchive-stage"><i class="material-icons">check_circle</i></a>
                        </span>
                    </span>
                </div>
                {{/each}}
            </div>
            {{else}}
                No stages yet -- add one below!
            {{/if}}
        </div>
    </script>
    {% endverbatim %}
</div>
<div id="formCard" class="form-card mdl-card mdl-cell--8-col mdl-cell--2-offset-desktop mdl-shadow--2dp mdl-grid">
    <div class="mdl-card__title">
        <h2 class="mdl-card__title-text">New Stage</h2>
    </div>
    <div class="mdl-card__supporting-text">
        <form method="post" action="{% url 'constellation_orderboard:api_v1_stage_create' %}" id="newStageForm" class="mdl-cell--2-offset-desktop mdl-cell--8-col">
            {% csrf_token %}
            {{ form.archived.as_hidden }}
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell--12-col mdl-cell--bottom">
                {{ form.name }}
                <label class="mdl-textfield__label" for="{{ form.name.id_for_label }}">Name</label>
            </div>
            <div class="mdl-card__actions">
                <div class="mdl-layout-spacer"></div>
                <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--primary">
                    Create Stage <i class="material-icons right">done</i>
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

constellation_orderboard/templates/constellation_orderboard/view-list.html
{% extends "constellation_base/base.html" %}

{% block title %}Orderboard | Manage Boards{% endblock %}
{% block heading %}Orderboard | Manage Boards{% endblock %}

{% block head %}
{{ block.super }}
{% load static %}
<link rel="stylesheet" href="{% static 'constellation_orderboard/css/orderboard.css' %}">
{% endblock %}

{% block js %}
<div id="message-toast" class="mdl-js-snackbar mdl-snackbar">
  <div class="mdl-snackbar__text"></div>
  <button class="mdl-snackbar__action" type="button"></button>
</div>
{{ block.super }}
{% load static %}
<script src="{% static 'constellation_orderboard/js/view-list.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.5/handlebars.min.js"></script>
<script>
    var url_api_v1_board_list = "{% url 'constellation_orderboard:api_v1_board_list' %}"
    var url_view_board = "{% url 'constellation_orderboard:view_board' 0 %}"
</script>
{% endblock %}

{% block content %}
<div id="boardsCard" class="mdl-card mdl-cell--8-col mdl-cell--2-offset-desktop mdl-shadow--2dp mdl-grid">
    {% verbatim %}
    <script id="handlebars-board" type="text/x-handlebars-template">
        <div class="mdl-card__title">
            <h2 class="mdl-card__title-text">Boards</h2>
        </div>
        <div class="mdl-card__supporting-text">
            <div class="mdl-list">
            {{#if boards}}
            {{#each boards}}
                <div class="mdl-list__item">
                    <span class="mdl-list__item-primary-content">
                        <a href="{{url}}">{{name}}</a>
                    </span>
                    <span class="mdl-list__item-secondary-content">
                        {{desc}}
                    </span>
                </div>
            {{/each}}
            {{else}}
                No active boards yet.
            {{/if}}
            </div>
        </div>
    </script>
    {% endverbatim %}
</div>
{% endblock %}